apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      service: {{ .Values.app.service }}
  template:
    metadata:
      labels:
        service: {{ .Values.app.service }}
    spec:
      containers:
        - image: {{ .Values.app.image }}
          name: {{ .Values.app.name }}
          ports:
            - name: rest
              containerPort: 3000
              protocol: TCP
          resources: {}
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
status: {}
