apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  type: NodePort
  ports:
    - name: rest
      port: 3000
      protocol: TCP
      targetPort: rest
  selector:
    service: {{ .Values.app.name }}
status:
  loadBalancer: {}
